### ISSUE TITLE
Trade station drain: feature already exists in vanilla

### ISSUE THREAD

**Issue by Vectorial1024** [DeadAirRT/deadair_scripts#2]
Not sure if this is known already, but in vanilla MD (checked 7.0), there is a script `md/drain_stations.xml` that regularly drains NPC trade station storage if the storage is high. "High-Drain-Factions" (~probably the Terran Protectorate~) will drain their trade station to 60% of storage while other factions will drain to 75%. This script is run every dozen minutes or so, and will run more frequently if the galaxy is larger.

And then DA Drain also claims to drain trade station storage.

Would this double-drain the storage? Should DA Fill no longer drain NPC trade stations because it is already handled by vanilla and the vanilla script is faster and more powerful?

**Comment by DeadAirRT** [comment]
The vanilla script has been present for a long time but they did quite a few changes for 7.0 stuff. It lacks any of the additional features of DA Fill (adjustable settings, ship mods, and injection of wares). I will monitor the balance impacts of terran potentially getting less ship mods than the other factions and go from there. Thanks for bringing it to my attention.

**Comment by Vectorial1024** [comment]
@DeadAirRT I went around to unpack the rest of the game files, and it turns out the "High-Drain-Faction" is **_not_** the Terran Protectorate, but is actually the Borons.

**Comment by DeadAirRT** [comment]
I set up some debug_text to actually check the amount drained and it was quite low from my testing (most of the time I didn't notice any at all). I believe my script still offers a much more effective solution to keep the economy moving when draining and with the performance improvements I've made over the years, I am not noticing any impacts.
