### ISSUE TITLE
Compatibility ROR <> GATE

### ISSUE THREAD

**Issue by Reisser696** [DeadAirRT/deadair_scripts#3]
In the past (i.e. with the old gate mod) there was a problem with Rise of the Ossian Raider. The gate used there did not appear as soon as "DeadAir Gate" was active. There was even a patch for it a long time ago at
https://forum.egosoft.com/viewtopic.php?t=409546 
which later no longer worked. 
Unfortunately I am not yet able to test this (new game) but in general it would be nice if both mods (yours and ROR) would work together, especially since I can no longer deactivate DeadAirGate separately.

**Comment by DeadAirRT** [comment]
There should be no incompatibility between the two unless we managed to choose within 40km of the same points in the same sectors for gates causing zone overlap. Not to mention, the version of gate that it had to be compatible with hasn't been around for several years now.

**Comment by Reisser696** [comment]
Thanks for the answer. I'll test it as soon as possible and let you know. It would be a shame if it didn't work - I would hate to do without either of the mods.

**Comment by Reisser696** [comment]
As you said: there are probably no problems with GATE and ROR. And also no more problems with the Xenon from the north - after I closed the gate there via your mod :D

**Comment by DeadAirRT** [comment]
Glad to hear. If any problems come up let me know.
